DROP SCHEMA IF EXISTS music;
CREATE SCHEMA IF NOT EXISTS music;
USE music;

CREATE TABLE IF NOT EXISTS Genre (
	idGenre INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    genre VARCHAR(255) NOT NULL
);

DESCRIBE Genre;

CREATE TABLE IF NOT EXISTS Album (
	idAlbum INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    albumName VARCHAR(255) NOT NULL,
    dateReleased DATETIME NOT NULL
);

DESCRIBE Album;

CREATE TABLE IF NOT EXISTS Artist (
	artistId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    artistName VARCHAR(255) NOT NULL
);

DESCRIBE Artist;